### ISSUE TITLE
进程号大于102400时会发生段错误

### ISSUE THREAD

**Issue by youzuoyong** [Tencent/Pebble#17]
文件src/common/coroutine.cpp 中定义数组
static stCoRoutineEnv_t* g_arrCoEnvPerThread[102400] = {0};

在函数coroutine_open()中直接使用pid作为下标，有可能导致数组下标越界错误。
虽然进程pid小于102400的概率比较小，但我确实遇到了。

**Comment by tatezhang** [comment]
对，这里确实是有风险的，应该获取pid_max动态分配

**Comment by tatezhang** [comment]
代码已提交
