### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by ChooseOne** [Tencent/Pebble#3]
cd build64_release/source/rpc;cp ../broadcast/libpebble_broadcast.a .;cp ../../thirdparty/consistent_hash/libconsistent_hash.a .;ar -x libpebble_broadcast.a;ar -x libconsistent_hash.a;ar -x common/libpebble_rpc_common.a;ar -x protocol/libpebble_rpc_protocol.a;ar -x transport/libpebble_rpc_transport.a;ar -x libpebble_rpc.a;ar -rcs libpebble_rpc_s.a *.o;rm *.o;rm libpebble_broadcast.a;rm libconsistent_hash.a
build64_release/source/rpc/compiler/cpp/src/pebble -r -out build64_release/tutorial/helloworld --gen cpp tutorial/helloworld/helloworld.pebble
Compiling build64_release/tutorial/broadcast/idl/broadcast_tutorial_BroadcastTrigger.cpp
cp: cannot stat '../../thirdparty/consistent_hash/libconsistent_hash.a': No such file or directory
ar: libconsistent_hash.a: No such file or directory
rm: cannot remove 'libconsistent_hash.a': No such file or directory

缺少库啊，编译错误

**Comment by tatezhang** [comment]
这个编译问题是BUILD文件中有个规则没有修改完善，已经提交
