### ISSUE TITLE
编译有一个错误

### ISSUE THREAD

**Issue by ka1nong** [Tencent/Pebble#7]
Blade(warning): Auto upgrade failure: /root/bin/blade: line 75: svn: command not found
Blade(warning): Please svn up /mnt/git_project/Pebble/tools/blade
Blade(warning): You can setenv BLADE_AUTO_UPGRADE=no to disable auto upgrade
Blade(info): loading BUILDs...
Blade(info): loading done.
Blade(info): analyzing dependency graph...
Blade(info): analyzing done.
Blade(info): generating build rules...
sh: 1: svn: not found
Blade(info): CPP=cpp
Blade(info): CC=gcc
Blade(info): CXX=g++
Blade(info): NVCC=nvcc
Blade(info): LD=g++
Blade(info): generating done.
Blade(info): tunes the parallel jobs number(-j N) to be 2
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build64_release
Updating version information
Compiling source/rpc/compiler/cpp/src/main.cc
Compiling source/rpc/compiler/cpp/src/thrifty.cc
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
scons: *** [build64_release/source/rpc/compiler/cpp/src/pebble.objs/main.cc.o] Error 4
thrifty.yy:28:0: warning: "__STDC_LIMIT_MACROS" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
thrifty.yy:29:0: warning: "__STDC_FORMAT_MACROS" redefined [enabled by default]
<command-line>:0:0: note: this is the location of the previous definition
{standard input}: Assembler messages:
{standard input}:5661: Warning: end of file not at end of a line; newline inserted
{standard input}:6328: Error: unknown pseudo-op: `.lvl5'
{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
scons: *** [build64_release/source/rpc/compiler/cpp/src/pebble.objs/thrifty.cc.o] Error 4
scons: building terminated because of errors.
Blade(error): building failure

请问这个是什么问题

**Comment by tatezhang** [comment]
Hi,方便加下qq吗？23899212

**Comment by tatezhang** [comment]
一般情况下是内存不够引起的，可以实际看下dmesg，如果机器内存紧张，可以减少并行编译任务：
blade build ... -j 1

**Comment by ka1nong** [comment]
好的，thx。应该是内存问题，只有1G的内存。
