### ISSUE TITLE
编译缺少libconsistent_hash.a库文件

### ISSUE THREAD

**Issue by WilliamWei1989** [Tencent/Pebble#8]
编译环境：
腾讯云机器
centos7.2
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

请问能建立一个pebble的交流群吗，出现问题方便及时沟通。谢谢~

编译错误信息：
build64_release/source/rpc/compiler/cpp/src/pebble -r -out build64_release/tutorial/helloworld --gen cpp tutorial/helloworld/helloworld.pebble
cd build64_release/source/rpc;cp ../broadcast/libpebble_broadcast.a .;cp ../../thirdparty/consistent_hash/libconsistent_hash.a .;ar -x libpebble_broadcast.a;ar -x libconsistent_hash.a;ar -x common/libpebble_rpc_common.a;ar -x protocol/libpebble_rpc_protocol.a;ar -x transport/libpebble_rpc_transport.a;ar -x libpebble_rpc.a;ar -rcs libpebble_rpc_s.a *.o;rm *.o;rm libpebble_broadcast.a;rm libconsistent_hash.a
cp: cannot stat '../../thirdparty/consistent_hash/libconsistent_hash.a': No such file or directory
ar: libconsistent_hash.a: No such file or directory
rm: cannot remove 'libconsistent_hash.a': No such file or directory
scons: *** [build64_release/source/rpc/libpebble_rpc_s.a] Error 1
scons: building terminated because of errors.
Blade(error): building failure

**Comment by tatezhang** [comment]
应该修正过，方便加下qq吗？23899212，详细确认下

**Comment by WilliamWei1989** [comment]
好的 我加下你~ 谢谢

**Comment by tatezhang** [comment]
之前已经提交了，BUILD文件一个命令未刷新导致的
